export const home: string;
export const header: string;
export const dataWrap: string;
export const income: string;
export const typeWrap: string;
export const left: string;
export const arrow: string;
export const contentWrap: string;
export const add: string;
